config/routes.rb
Rails.application.routes.draw do
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :body, presence: true

  def tag_id
    "post_#{self.id}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    layout_rendering = (params[:skip_layout] == "yes") ? false : true
    render "index", layout: layout_rendering
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html do
          redirect_to posts_url
        end
        format.turbo_stream do
          render turbo_stream: turbo_stream.append('list',  
                                                      partial: "posts/line",
                                                      locals: { post: @post, notice: "Post created!" })
        end

      else
        format.html do
          render "edit", locals: { post: @post }
        end
        format.turbo_stream do
          render turbo_stream: turbo_stream.update('modal',
                                                      partial: "posts/modal_form",
                                                      locals: { post: @post }), status: 400
        end

      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html do
          redirect_to posts_url
        end
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(@post.tag_id,
                                                    partial: "posts/line",
                                                    locals: { post: @post })
        end

      else
        format.html do
          render "edit", locals: { post: @post }
        end
        format.turbo_stream do
          render turbo_stream: turbo_stream.update('modal',
                                                    partial: "posts/modal_form",
                                                    locals: { post: @post }), status: 400
        end

      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html do
        redirect_to posts_url
      end
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(@post.tag_id,
                                                  partial: "posts/line",
                                                  locals: { post: @post, deleted: "yes" })
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TurboModal</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_pack_tag "application" %>
  <%= javascript_pack_tag 'application', 'data-turbo-track': 'reload' %>

</head>

<body class="h-full font-sans antialiased font-normal leading-normal bg-gray-100">
<%= yield %>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, data: { controller: 'post-form', action: 'turbo:submit-end->post-modal#close_if_ok' }) do |form| %>
  <div class="px-4 pt-5 pb-4 sm:p-6 sm:pb-4">

    <% if form.object.errors.any? %>
      <div class="alert alert-error mb-6" role="alert">
        <div class="flex items-start justify-start">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" class="fill-current icon mr-4 mt-1 flex-no-shrink" role="img" aria-labelledby="f1yx75u7nv0lvn6ck4z10w7lksjmk2f">
            <title id="f1yx75u7nv0lvn6ck4z10w7lksjmk2f">Icons/close outline</title>
            <path d="M2.93 17.07A10 10 0 1 1 17.07 2.93 10 10 0 0 1 2.93 17.07zm1.41-1.41A8 8 0 1 0 15.66 4.34 8 8 0 0 0 4.34 15.66zm9.9-8.49L11.41 10l2.83 2.83-1.41 1.41L10 11.41l-2.83 2.83-1.41-1.41L8.59 10 5.76 7.17l1.41-1.41L10 8.59l2.83-2.83 1.41 1.41z">

            </path>
          </svg>

          <div>
            <h4 class="font-black text-sm uppercase tracking">
              <%= pluralize(form.object.errors.count, "error") %> prohibited this post from being saved:
            </h4>
            <ul>
              <% form.object.errors.full_messages.each do |message| %>
                <li><%= message %>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :body %>
      <%= form.text_area :body, class: "form-control" %>
    </div>

  </div>
  <div class="bg-gray-50 rounded-b px-4 py-3 sm:px-6 mt-5 sm:mt-6 sm:grid sm:grid-cols-2 sm:gap-3 sm:grid-flow-row-dense">
    <%= form.button class: "w-full btn btn-primary sm:col-start-2" %>
    <%= link_to "Cancel", posts_url, "data-action": "click->post-modal#close", class: "mt-3 w-full btn btn-white sm:mt-0 sm:col-start-1" %>

  </div>
<% end %>

<% if post.persisted? %>
  <%= button_to 'Delete', post, class: "mt-3 w-full btn sm:mt-0 hover:bg-red-600 transition-all duration-500 ease-in-out", method: :delete, form: { data: {controller: "delete", action: 'submit->delete#confirm turbo:submit-end->delete#exit', "delete-confirm-message-value": "Are you sure?"} } %>
<% end %>

app/views/posts/_line.html.erb
<!-- Unable to use the turbo_frame_tag inside a table, see https://github.com/hotwired/turbo/issues/48 -->

<tr id="<%= post.tag_id %>" <%= "data-controller='fadeout'".html_safe if defined?(deleted) %>>
    
    <td class="px-6 py-4 whitespace-nowrap text-sm leading-5 text-cool-gray-900">
    <%= post.title %>
    </td>
    <td class="px-6 py-4 whitespace-nowrap text-sm leading-5 text-cool-gray-500">
    <%= post.body %>
    </td>
    <td class="px-6 py-4 whitespace-nowrap text-sm leading-5 text-cool-gray-500">
        <% if !defined?(deleted) %>
            <%= turbo_frame_tag post do %>
                <div data-controller="link">
                    <%= link_to 'Edit', edit_post_path(post), class: "float-right btn btn-secondary transition duration-500 ease-in-out hover:bg-green-700", data: { link_target: "link", action: "click->link#open", "turbo-frame": "modal" } %>
                </div>
            <% end %>
        <% else  %>
            <span class="text-red">Deleted</>
        <% end %>

        <% if notice %>
        <div class="fixed inset-x-0 top-0 flex items-end justify-right px-4 py-6 sm:p-6 justify-end z-30 pointer-events-none">
        <div data-controller="alert" class="max-w-sm w-full shadow-lg rounded px-4 py-3 rounded relative bg-green-400 border-l-4 border-green-700 text-white pointer-events-auto">
            <div class="p-2">
            <div class="flex items-start">
                <div class="ml-3 w-0 flex-1 pt-0.5">
                <p class="text-sm leading-5 font-medium">
                    <%= notice %>
                </p>
                </div>
                <div class="ml-4 flex-shrink-0 flex">
                <button data-action="alert#close" class="inline-flex text-white focus:outline-none focus:text-gray-300 transition ease-in-out duration-150">
                    <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                    <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"/>
                    </svg>
                </button>
                </div>
            </div>
            </div>
        </div>
        <% end %>

    </td>
</tr>

app/views/posts/_list.html.erb
<% @posts.each do |post| %>
    <%= render partial: 'line', locals: {post: post} %>
<% end %>

app/views/posts/_modal_form.html.erb
<%= turbo_frame_tag "modal" do %>
  <div data-post-modal-target="container" data-action="click->post-modal#closeBackground keyup@window->post-modal#closeWithKeyboard"
      class="hidden animated fadeIn fixed inset-0 overflow-y-auto flex items-center justify-center"
      style="z-index: 9999;">
    <!-- Modal Inner Container -->
    <div class="max-w-lg max-h-screen w-full relative">
      <!-- Modal Card -->
      <div class="m-1 bg-white rounded shadow">

        <div class="px-4 py-5 border-b border-gray-200 sm:px-6">
          <h3 class="text-lg leading-6 font-medium text-gray-900">
            Post
          </h3>
        </div>
          <%= render partial: "form", locals: { post: @post } %>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container mx-auto">
    <div class="mx-auto max-w-lg max-h-screen mt-8 w-full relative">
        <div class="m-1 bg-white rounded shadow-2xl">
            <%= render partial: "modal_form", locals: {post: @post} %>
        </div>        
    </div>
</div>

<div data-controller="swap-body" data-swap-body-match-value="edit" data-swap-body-url-value="/posts?skip_layout=yes"></div>

app/views/posts/index.html.erb
<% if notice %>
  <div class="flex items-center bg-blue-100 text-blue-600 text-sm justify-center font-bold px-4 py-3" role="alert">
    <svg class="fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
      <path d="M12.432 0c1.34 0 2.01.912 2.01 1.957 0 1.305-1.164 2.512-2.679 2.512-1.269 0-2.009-.75-1.974-1.99C9.789 1.436 10.67 0 12.432 0zM8.309 20c-1.058 0-1.833-.652-1.093-3.524l1.214-5.092c.211-.814.246-1.141 0-1.141-.317 0-1.689.562-2.502 1.117l-.528-.88c2.572-2.186 5.531-3.467 6.801-3.467 1.057 0 1.233 1.273.705 3.23l-1.391 5.352c-.246.945-.141 1.271.106 1.271.317 0 1.357-.392 2.379-1.207l.6.814C12.098 19.02 9.365 20 8.309 20z"/>
    </svg>
    <p><%= notice %></p>
  </div>
<% end %>

<% if alert %>
  <div class="flex items-center bg-yellow-100 text-yellow-600 justify-center text-sm font-bold px-4 py-3" role="alert">
    <svg class="fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
      <path d="M12.432 0c1.34 0 2.01.912 2.01 1.957 0 1.305-1.164 2.512-2.679 2.512-1.269 0-2.009-.75-1.974-1.99C9.789 1.436 10.67 0 12.432 0zM8.309 20c-1.058 0-1.833-.652-1.093-3.524l1.214-5.092c.211-.814.246-1.141 0-1.141-.317 0-1.689.562-2.502 1.117l-.528-.88c2.572-2.186 5.531-3.467 6.801-3.467 1.057 0 1.233 1.273.705 3.23l-1.391 5.352c-.246.945-.141 1.271.106 1.271.317 0 1.357-.392 2.379-1.207l.6.814C12.098 19.02 9.365 20 8.309 20z"/>
    </svg>
    <p><%= alert %></p>
  </div>
<% end %>


<div class="mt-8" data-controller="post-modal" data-post-modal-index-url-value="/posts" data-post-modal-focus-field-value="post_title" data-post-modal-prevent-default-action-opening="false">

  <div class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="-ml-4 -mt-2 flex items-center justify-between flex-wrap sm:flex-no-wrap">
      <div>
        <h2 class="max-w-6xl mx-auto mt-8 px-4 text-lg leading-6 font-medium text-cool-gray-900 sm:px-6 lg:px-8">
          Posts
        </h2>
      </div>
      <div>
        <span class="inline-flex rounded-md shadow-sm">
            <div data-controller="link">
              <%= link_to 'New Post', new_post_path, class: "btn btn-primary", data: { link_target: "link", action: "click->link#open", "turbo-frame": "modal" } %>
            </div>
        </span>
      </div>
    </div>
  </div>

  <div class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex flex-col mt-2">
      <div class="align-middle min-w-full overflow-x-auto shadow overflow-hidden sm:rounded-lg">
        <table class="min-w-full divide-y divide-cool-gray-200">
          <thead>
          <tr>
            <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-cool-gray-500 uppercase tracking-wider">Title</th>
            <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-cool-gray-500 uppercase tracking-wider">Body</th>
            <th colspan="1" class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-cool-gray-500 uppercase tracking-wider"></th>
          </tr>
          </thead>
          <tbody id="list" class="bg-white divide-y divide-cool-gray-200">

          <%= render partial: 'list' %>

          </tbody>
        </table>
      </div>
    </div>
  </div>

  <%= turbo_frame_tag "modal" do %>
  <% end %>

</div>

<div data-controller="popstate" data-popstate-match-links-value="new|edit"></div>

app/views/posts/new.html.erb
<div class="container mx-auto">
    <div class="mx-auto max-w-lg max-h-screen mt-8 w-full relative">
        <div class="m-1 bg-white rounded shadow-2xl">
            <%= render partial: "modal_form", locals: {post: @post} %>
        </div>
    </div>
</div>        

<div data-controller="swap-body" data-swap-body-match-value="new" data-swap-body-url-value="/posts?skip_layout=yes"></div>